apiVersion: v1
kind: Service
metadata:
  name: math-api-login-mongo
  labels:
    k8s-app: math-api-login-mongo
spec:
  ports:
    - name: tcp-49161-3000-4rrtm
      protocol: TCP
      port: 49161
      targetPort: 3000
  selector:
    k8s-app: math-api-login-mongo
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost